USE ARMY CREATE ROLE Admin
USE ARMY CREATE ROLE Boss


GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Commissar TO Admin
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Doctor TO Admin
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Recruit TO Admin
GRANT SELECT, INSERT, UPDATE, DELETE ON dbo.Draft_Board TO Admin

GRANT SELECT ON dbo.Draft_Board TO Boss


CREATE LOGIN Adm WITH PASSWORD='12345', CHECK_EXPIRATION=OFF
CREATE LOGIN Boss1 WITH PASSWORD='54321', CHECK_EXPIRATION=OFF


USE ARMY CREATE USER userAdm FOR LOGIN Adm
USE ARMY CREATE USER userBoss FOR LOGIN Boss1


USE ARMY ALTER ROLE Admin ADD MEMBER userAdm
USE ARMY ALTER ROLE Boss ADD MEMBER userBoss